on:
  push:
    branches: typescript

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Install dependancies
        uses: actions/setup-node@v5
        with:
          node-version: 20
        
      - name: Generate a build
        run: |
          npm install
          npm run build

      - name: Generate a short hash
        id: hash
        run: echo "short_hash=$(echo "${GITHUB_SHA}" | cut -c1-7)" >> $GITHUB_OUTPUT
      
      - name: Generate a tag
        run: git tag ${{ steps.hash.outputs.short_hash }}
      
      - name: Generate a release
        uses: softprops/action-gh-release@v2
        with:
          files: build.zip
          make_latest: true
          tag_name: ${{ steps.hash.outputs.short_hash }}
          
          
